import os
import shutil
import sys

try:
    import winshell
    from win32com.client import Dispatch
except ImportError as e:
    print("Required module is not installed:", e)
    print("Please run 'pip install pywin32' and 'pip install winshell'")
    sys.exit(1)

def create_shortcut(target, shortcut_path, icon_path=None):
    """
    Create a shortcut at the specified path.
    
    Parameters:
    - target: Path to the executable file.
    - shortcut_path: Path where the shortcut should be created.
    - icon_path: (Optional) Path to an icon file for the shortcut.
    """
    shell = Dispatch('WScript.Shell')
    shortcut = shell.CreateShortcut(shortcut_path)
    shortcut.TargetPath = target
    if icon_path:
        shortcut.IconLocation = icon_path
    shortcut.save()

def install_program(source_exe, new_exe_name, icon_path):
    """
    Install the program by copying the executable to the Program Files directory,
    renaming it, and creating a shortcut on the desktop.
    
    Parameters:
    - source_exe: Path to the source executable file.
    - new_exe_name: New name for the executable file.
    - icon_path: Path to the icon file.
    """
    # Define the program directory in Program Files
    program_dir = os.path.join(os.environ['ProgramFiles'], 'YourProgramName')
    
    # Get the path to the current user's desktop
    desktop = winshell.desktop()
    
    # Define the path for the shortcut on the desktop
    shortcut_path = os.path.join(desktop, 'YourProgram.lnk')

    # Create the program directory if it doesn't exist
    if not os.path.exists(program_dir):
        os.makedirs(program_dir)

    # Define the new path for the executable with the new name
    target_exe = os.path.join(program_dir, new_exe_name)

    # Copy the executable to the program directory and rename it
    shutil.copyfile(source_exe, target_exe)

    # Set the icon for the executable
    if os.path.exists(icon_path):
        shutil.copyfile(icon_path, os.path.join(program_dir, 'myicon.ico'))

    # Create a shortcut on the desktop with the icon
    create_shortcut(target_exe, shortcut_path, os.path.join(program_dir, 'myicon.ico'))

    print(f'Installation complete. Shortcut created at {shortcut_path}')

if __name__ == '__main__':
    # Replace this with the actual path to your executable file generated by PyInstaller
    source_exe = 'C:\\path_to_your_executable\\myscript.exe'
    # Define the new name for the executable
    new_exe_name = 'YourNewProgramName.exe'
    # Replace this with the actual path to your icon file
    icon_path = 'C:\\path_to_your_icon\\myicon.ico'
    install_program(source_exe, new_exe_name, icon_path)
